# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wahyu/bee165b

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wahyu/bee165b

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/wahyu/bee165b/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wahyu/bee165b/CMakeFiles /home/wahyu/bee165b/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wahyu/bee165b/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build_bundled_libs

# Build rule for target.
build_bundled_libs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build_bundled_libs
.PHONY : build_bundled_libs

# fast build rule for target.
build_bundled_libs/fast:
	$(MAKE) -f CMakeFiles/build_bundled_libs.dir/build.make CMakeFiles/build_bundled_libs.dir/build
.PHONY : build_bundled_libs/fast

#=============================================================================
# Target rules for targets named cjson

# Build rule for target.
cjson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cjson
.PHONY : cjson

# fast build rule for target.
cjson/fast:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/build
.PHONY : cjson/fast

#=============================================================================
# Target rules for targets named coro

# Build rule for target.
coro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coro
.PHONY : coro

# fast build rule for target.
coro/fast:
	$(MAKE) -f CMakeFiles/coro.dir/build.make CMakeFiles/coro.dir/build
.PHONY : coro/fast

#=============================================================================
# Target rules for targets named eio

# Build rule for target.
eio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eio
.PHONY : eio

# fast build rule for target.
eio/fast:
	$(MAKE) -f CMakeFiles/eio.dir/build.make CMakeFiles/eio.dir/build
.PHONY : eio/fast

#=============================================================================
# Target rules for targets named ev

# Build rule for target.
ev: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ev
.PHONY : ev

# fast build rule for target.
ev/fast:
	$(MAKE) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/build
.PHONY : ev/fast

#=============================================================================
# Target rules for targets named gopt

# Build rule for target.
gopt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gopt
.PHONY : gopt

# fast build rule for target.
gopt/fast:
	$(MAKE) -f CMakeFiles/gopt.dir/build.make CMakeFiles/gopt.dir/build
.PHONY : gopt/fast

#=============================================================================
# Target rules for targets named libluajit

# Build rule for target.
libluajit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libluajit
.PHONY : libluajit

# fast build rule for target.
libluajit/fast:
	$(MAKE) -f CMakeFiles/libluajit.dir/build.make CMakeFiles/libluajit.dir/build
.PHONY : libluajit/fast

#=============================================================================
# Target rules for targets named libsham

# Build rule for target.
libsham: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsham
.PHONY : libsham

# fast build rule for target.
libsham/fast:
	$(MAKE) -f CMakeFiles/libsham.dir/build.make CMakeFiles/libsham.dir/build
.PHONY : libsham/fast

#=============================================================================
# Target rules for targets named misc

# Build rule for target.
misc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 misc
.PHONY : misc

# fast build rule for target.
misc/fast:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/build
.PHONY : misc/fast

#=============================================================================
# Target rules for targets named tags

# Build rule for target.
tags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tags
.PHONY : tags

# fast build rule for target.
tags/fast:
	$(MAKE) -f CMakeFiles/tags.dir/build.make CMakeFiles/tags.dir/build
.PHONY : tags/fast

#=============================================================================
# Target rules for targets named yaml

# Build rule for target.
yaml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yaml
.PHONY : yaml

# fast build rule for target.
yaml/fast:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/build
.PHONY : yaml/fast

#=============================================================================
# Target rules for targets named bee

# Build rule for target.
bee: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bee
.PHONY : bee

# fast build rule for target.
bee/fast:
	$(MAKE) -f src/CMakeFiles/bee.dir/build.make src/CMakeFiles/bee.dir/build
.PHONY : bee/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f src/CMakeFiles/core.dir/build.make src/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named generate_lua_sources

# Build rule for target.
generate_lua_sources: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_lua_sources
.PHONY : generate_lua_sources

# fast build rule for target.
generate_lua_sources/fast:
	$(MAKE) -f src/CMakeFiles/generate_lua_sources.dir/build.make src/CMakeFiles/generate_lua_sources.dir/build
.PHONY : generate_lua_sources/fast

#=============================================================================
# Target rules for targets named ragel

# Build rule for target.
ragel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ragel
.PHONY : ragel

# fast build rule for target.
ragel/fast:
	$(MAKE) -f src/CMakeFiles/ragel.dir/build.make src/CMakeFiles/ragel.dir/build
.PHONY : ragel/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f src/CMakeFiles/server.dir/build.make src/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named generate_module_api

# Build rule for target.
generate_module_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_module_api
.PHONY : generate_module_api

# fast build rule for target.
generate_module_api/fast:
	$(MAKE) -f src/trivia/CMakeFiles/generate_module_api.dir/build.make src/trivia/CMakeFiles/generate_module_api.dir/build
.PHONY : generate_module_api/fast

#=============================================================================
# Target rules for targets named msgpuck

# Build rule for target.
msgpuck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msgpuck
.PHONY : msgpuck

# fast build rule for target.
msgpuck/fast:
	$(MAKE) -f src/lib/CMakeFiles/msgpuck.dir/build.make src/lib/CMakeFiles/msgpuck.dir/build
.PHONY : msgpuck/fast

#=============================================================================
# Target rules for targets named bit

# Build rule for target.
bit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bit
.PHONY : bit

# fast build rule for target.
bit/fast:
	$(MAKE) -f src/lib/bit/CMakeFiles/bit.dir/build.make src/lib/bit/CMakeFiles/bit.dir/build
.PHONY : bit/fast

#=============================================================================
# Target rules for targets named bitset

# Build rule for target.
bitset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bitset
.PHONY : bitset

# fast build rule for target.
bitset/fast:
	$(MAKE) -f src/lib/bitset/CMakeFiles/bitset.dir/build.make src/lib/bitset/CMakeFiles/bitset.dir/build
.PHONY : bitset/fast

#=============================================================================
# Target rules for targets named small

# Build rule for target.
small: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 small
.PHONY : small

# fast build rule for target.
small/fast:
	$(MAKE) -f src/lib/small/CMakeFiles/small.dir/build.make src/lib/small/CMakeFiles/small.dir/build
.PHONY : small/fast

#=============================================================================
# Target rules for targets named salad

# Build rule for target.
salad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 salad
.PHONY : salad

# fast build rule for target.
salad/fast:
	$(MAKE) -f src/lib/salad/CMakeFiles/salad.dir/build.make src/lib/salad/CMakeFiles/salad.dir/build
.PHONY : salad/fast

#=============================================================================
# Target rules for targets named db

# Build rule for target.
db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db
.PHONY : db

# fast build rule for target.
db/fast:
	$(MAKE) -f src/db/CMakeFiles/db.dir/build.make src/db/CMakeFiles/db.dir/build
.PHONY : db/fast

#=============================================================================
# Target rules for targets named db_generate_lua_sources

# Build rule for target.
db_generate_lua_sources: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_generate_lua_sources
.PHONY : db_generate_lua_sources

# fast build rule for target.
db_generate_lua_sources/fast:
	$(MAKE) -f src/db/CMakeFiles/db_generate_lua_sources.dir/build.make src/db/CMakeFiles/db_generate_lua_sources.dir/build
.PHONY : db_generate_lua_sources/fast

#=============================================================================
# Target rules for targets named bin2c

# Build rule for target.
bin2c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin2c
.PHONY : bin2c

# fast build rule for target.
bin2c/fast:
	$(MAKE) -f extra/CMakeFiles/bin2c.dir/build.make extra/CMakeFiles/bin2c.dir/build
.PHONY : bin2c/fast

#=============================================================================
# Target rules for targets named txt2c

# Build rule for target.
txt2c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 txt2c
.PHONY : txt2c

# fast build rule for target.
txt2c/fast:
	$(MAKE) -f extra/CMakeFiles/txt2c.dir/build.make extra/CMakeFiles/txt2c.dir/build
.PHONY : txt2c/fast

#=============================================================================
# Target rules for targets named man-beectl

# Build rule for target.
man-beectl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man-beectl
.PHONY : man-beectl

# fast build rule for target.
man-beectl/fast:
	$(MAKE) -f extra/dist/CMakeFiles/man-beectl.dir/build.make extra/dist/CMakeFiles/man-beectl.dir/build
.PHONY : man-beectl/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f test/CMakeFiles/test.dir/build.make test/CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test-force

# Build rule for target.
test-force: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-force
.PHONY : test-force

# fast build rule for target.
test-force/fast:
	$(MAKE) -f test/CMakeFiles/test-force.dir/build.make test/CMakeFiles/test-force.dir/build
.PHONY : test-force/fast

#=============================================================================
# Target rules for targets named module_api

# Build rule for target.
module_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 module_api
.PHONY : module_api

# fast build rule for target.
module_api/fast:
	$(MAKE) -f test/app/CMakeFiles/module_api.dir/build.make test/app/CMakeFiles/module_api.dir/build
.PHONY : module_api/fast

#=============================================================================
# Target rules for targets named arena_mt.test

# Build rule for target.
arena_mt.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arena_mt.test
.PHONY : arena_mt.test

# fast build rule for target.
arena_mt.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/arena_mt.test.dir/build.make test/unit/CMakeFiles/arena_mt.test.dir/build
.PHONY : arena_mt.test/fast

#=============================================================================
# Target rules for targets named base64.test

# Build rule for target.
base64.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base64.test
.PHONY : base64.test

# fast build rule for target.
base64.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/base64.test.dir/build.make test/unit/CMakeFiles/base64.test.dir/build
.PHONY : base64.test/fast

#=============================================================================
# Target rules for targets named bit.test

# Build rule for target.
bit.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bit.test
.PHONY : bit.test

# fast build rule for target.
bit.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/bit.test.dir/build.make test/unit/CMakeFiles/bit.test.dir/build
.PHONY : bit.test/fast

#=============================================================================
# Target rules for targets named bitset_basic.test

# Build rule for target.
bitset_basic.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bitset_basic.test
.PHONY : bitset_basic.test

# fast build rule for target.
bitset_basic.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/bitset_basic.test.dir/build.make test/unit/CMakeFiles/bitset_basic.test.dir/build
.PHONY : bitset_basic.test/fast

#=============================================================================
# Target rules for targets named bitset_index.test

# Build rule for target.
bitset_index.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bitset_index.test
.PHONY : bitset_index.test

# fast build rule for target.
bitset_index.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/bitset_index.test.dir/build.make test/unit/CMakeFiles/bitset_index.test.dir/build
.PHONY : bitset_index.test/fast

#=============================================================================
# Target rules for targets named bitset_iterator.test

# Build rule for target.
bitset_iterator.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bitset_iterator.test
.PHONY : bitset_iterator.test

# fast build rule for target.
bitset_iterator.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/bitset_iterator.test.dir/build.make test/unit/CMakeFiles/bitset_iterator.test.dir/build
.PHONY : bitset_iterator.test/fast

#=============================================================================
# Target rules for targets named bps_tree.test

# Build rule for target.
bps_tree.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bps_tree.test
.PHONY : bps_tree.test

# fast build rule for target.
bps_tree.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/bps_tree.test.dir/build.make test/unit/CMakeFiles/bps_tree.test.dir/build
.PHONY : bps_tree.test/fast

#=============================================================================
# Target rules for targets named bps_tree_itr.test

# Build rule for target.
bps_tree_itr.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bps_tree_itr.test
.PHONY : bps_tree_itr.test

# fast build rule for target.
bps_tree_itr.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/bps_tree_itr.test.dir/build.make test/unit/CMakeFiles/bps_tree_itr.test.dir/build
.PHONY : bps_tree_itr.test/fast

#=============================================================================
# Target rules for targets named coio.test

# Build rule for target.
coio.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coio.test
.PHONY : coio.test

# fast build rule for target.
coio.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/coio.test.dir/build.make test/unit/CMakeFiles/coio.test.dir/build
.PHONY : coio.test/fast

#=============================================================================
# Target rules for targets named fiber.test

# Build rule for target.
fiber.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fiber.test
.PHONY : fiber.test

# fast build rule for target.
fiber.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/fiber.test.dir/build.make test/unit/CMakeFiles/fiber.test.dir/build
.PHONY : fiber.test/fast

#=============================================================================
# Target rules for targets named fiber_stress.test

# Build rule for target.
fiber_stress.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fiber_stress.test
.PHONY : fiber_stress.test

# fast build rule for target.
fiber_stress.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/fiber_stress.test.dir/build.make test/unit/CMakeFiles/fiber_stress.test.dir/build
.PHONY : fiber_stress.test/fast

#=============================================================================
# Target rules for targets named find_path.test

# Build rule for target.
find_path.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 find_path.test
.PHONY : find_path.test

# fast build rule for target.
find_path.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/find_path.test.dir/build.make test/unit/CMakeFiles/find_path.test.dir/build
.PHONY : find_path.test/fast

#=============================================================================
# Target rules for targets named fiob.test

# Build rule for target.
fiob.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fiob.test
.PHONY : fiob.test

# fast build rule for target.
fiob.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/fiob.test.dir/build.make test/unit/CMakeFiles/fiob.test.dir/build
.PHONY : fiob.test/fast

#=============================================================================
# Target rules for targets named guava.test

# Build rule for target.
guava.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 guava.test
.PHONY : guava.test

# fast build rule for target.
guava.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/guava.test.dir/build.make test/unit/CMakeFiles/guava.test.dir/build
.PHONY : guava.test/fast

#=============================================================================
# Target rules for targets named int96.test

# Build rule for target.
int96.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 int96.test
.PHONY : int96.test

# fast build rule for target.
int96.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/int96.test.dir/build.make test/unit/CMakeFiles/int96.test.dir/build
.PHONY : int96.test/fast

#=============================================================================
# Target rules for targets named ipc.test

# Build rule for target.
ipc.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ipc.test
.PHONY : ipc.test

# fast build rule for target.
ipc.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/ipc.test.dir/build.make test/unit/CMakeFiles/ipc.test.dir/build
.PHONY : ipc.test/fast

#=============================================================================
# Target rules for targets named lf_lifo.test

# Build rule for target.
lf_lifo.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lf_lifo.test
.PHONY : lf_lifo.test

# fast build rule for target.
lf_lifo.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/lf_lifo.test.dir/build.make test/unit/CMakeFiles/lf_lifo.test.dir/build
.PHONY : lf_lifo.test/fast

#=============================================================================
# Target rules for targets named light.test

# Build rule for target.
light.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 light.test
.PHONY : light.test

# fast build rule for target.
light.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/light.test.dir/build.make test/unit/CMakeFiles/light.test.dir/build
.PHONY : light.test/fast

#=============================================================================
# Target rules for targets named matras.test

# Build rule for target.
matras.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matras.test
.PHONY : matras.test

# fast build rule for target.
matras.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/matras.test.dir/build.make test/unit/CMakeFiles/matras.test.dir/build
.PHONY : matras.test/fast

#=============================================================================
# Target rules for targets named mempool.test

# Build rule for target.
mempool.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mempool.test
.PHONY : mempool.test

# fast build rule for target.
mempool.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/mempool.test.dir/build.make test/unit/CMakeFiles/mempool.test.dir/build
.PHONY : mempool.test/fast

#=============================================================================
# Target rules for targets named mhash.test

# Build rule for target.
mhash.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mhash.test
.PHONY : mhash.test

# fast build rule for target.
mhash.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/mhash.test.dir/build.make test/unit/CMakeFiles/mhash.test.dir/build
.PHONY : mhash.test/fast

#=============================================================================
# Target rules for targets named mhash_bytemap.test

# Build rule for target.
mhash_bytemap.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mhash_bytemap.test
.PHONY : mhash_bytemap.test

# fast build rule for target.
mhash_bytemap.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/mhash_bytemap.test.dir/build.make test/unit/CMakeFiles/mhash_bytemap.test.dir/build
.PHONY : mhash_bytemap.test/fast

#=============================================================================
# Target rules for targets named msgpack.test

# Build rule for target.
msgpack.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msgpack.test
.PHONY : msgpack.test

# fast build rule for target.
msgpack.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/msgpack.test.dir/build.make test/unit/CMakeFiles/msgpack.test.dir/build
.PHONY : msgpack.test/fast

#=============================================================================
# Target rules for targets named queue.test

# Build rule for target.
queue.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queue.test
.PHONY : queue.test

# fast build rule for target.
queue.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/queue.test.dir/build.make test/unit/CMakeFiles/queue.test.dir/build
.PHONY : queue.test/fast

#=============================================================================
# Target rules for targets named quota.test

# Build rule for target.
quota.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quota.test
.PHONY : quota.test

# fast build rule for target.
quota.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/quota.test.dir/build.make test/unit/CMakeFiles/quota.test.dir/build
.PHONY : quota.test/fast

#=============================================================================
# Target rules for targets named region.test

# Build rule for target.
region.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 region.test
.PHONY : region.test

# fast build rule for target.
region.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/region.test.dir/build.make test/unit/CMakeFiles/region.test.dir/build
.PHONY : region.test/fast

#=============================================================================
# Target rules for targets named rlist.test

# Build rule for target.
rlist.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rlist.test
.PHONY : rlist.test

# fast build rule for target.
rlist.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/rlist.test.dir/build.make test/unit/CMakeFiles/rlist.test.dir/build
.PHONY : rlist.test/fast

#=============================================================================
# Target rules for targets named rope.test

# Build rule for target.
rope.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rope.test
.PHONY : rope.test

# fast build rule for target.
rope.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/rope.test.dir/build.make test/unit/CMakeFiles/rope.test.dir/build
.PHONY : rope.test/fast

#=============================================================================
# Target rules for targets named rope_avl.test

# Build rule for target.
rope_avl.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rope_avl.test
.PHONY : rope_avl.test

# fast build rule for target.
rope_avl.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/rope_avl.test.dir/build.make test/unit/CMakeFiles/rope_avl.test.dir/build
.PHONY : rope_avl.test/fast

#=============================================================================
# Target rules for targets named rope_basic.test

# Build rule for target.
rope_basic.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rope_basic.test
.PHONY : rope_basic.test

# fast build rule for target.
rope_basic.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/rope_basic.test.dir/build.make test/unit/CMakeFiles/rope_basic.test.dir/build
.PHONY : rope_basic.test/fast

#=============================================================================
# Target rules for targets named rope_stress.test

# Build rule for target.
rope_stress.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rope_stress.test
.PHONY : rope_stress.test

# fast build rule for target.
rope_stress.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/rope_stress.test.dir/build.make test/unit/CMakeFiles/rope_stress.test.dir/build
.PHONY : rope_stress.test/fast

#=============================================================================
# Target rules for targets named rtree.test

# Build rule for target.
rtree.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtree.test
.PHONY : rtree.test

# fast build rule for target.
rtree.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/rtree.test.dir/build.make test/unit/CMakeFiles/rtree.test.dir/build
.PHONY : rtree.test/fast

#=============================================================================
# Target rules for targets named rtree_itr.test

# Build rule for target.
rtree_itr.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtree_itr.test
.PHONY : rtree_itr.test

# fast build rule for target.
rtree_itr.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/rtree_itr.test.dir/build.make test/unit/CMakeFiles/rtree_itr.test.dir/build
.PHONY : rtree_itr.test/fast

#=============================================================================
# Target rules for targets named scramble.test

# Build rule for target.
scramble.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scramble.test
.PHONY : scramble.test

# fast build rule for target.
scramble.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/scramble.test.dir/build.make test/unit/CMakeFiles/scramble.test.dir/build
.PHONY : scramble.test/fast

#=============================================================================
# Target rules for targets named slab_arena.test

# Build rule for target.
slab_arena.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slab_arena.test
.PHONY : slab_arena.test

# fast build rule for target.
slab_arena.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/slab_arena.test.dir/build.make test/unit/CMakeFiles/slab_arena.test.dir/build
.PHONY : slab_arena.test/fast

#=============================================================================
# Target rules for targets named slab_cache.test

# Build rule for target.
slab_cache.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slab_cache.test
.PHONY : slab_cache.test

# fast build rule for target.
slab_cache.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/slab_cache.test.dir/build.make test/unit/CMakeFiles/slab_cache.test.dir/build
.PHONY : slab_cache.test/fast

#=============================================================================
# Target rules for targets named small_alloc.test

# Build rule for target.
small_alloc.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 small_alloc.test
.PHONY : small_alloc.test

# fast build rule for target.
small_alloc.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/small_alloc.test.dir/build.make test/unit/CMakeFiles/small_alloc.test.dir/build
.PHONY : small_alloc.test/fast

#=============================================================================
# Target rules for targets named uri.test

# Build rule for target.
uri.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uri.test
.PHONY : uri.test

# fast build rule for target.
uri.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/uri.test.dir/build.make test/unit/CMakeFiles/uri.test.dir/build
.PHONY : uri.test/fast

#=============================================================================
# Target rules for targets named vclock.test

# Build rule for target.
vclock.test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vclock.test
.PHONY : vclock.test

# fast build rule for target.
vclock.test/fast:
	$(MAKE) -f test/unit/CMakeFiles/vclock.test.dir/build.make test/unit/CMakeFiles/vclock.test.dir/build
.PHONY : vclock.test/fast

#=============================================================================
# Target rules for targets named man-bee

# Build rule for target.
man-bee: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man-bee
.PHONY : man-bee

# fast build rule for target.
man-bee/fast:
	$(MAKE) -f doc/man/CMakeFiles/man-bee.dir/build.make doc/man/CMakeFiles/man-bee.dir/build
.PHONY : man-bee/fast

#=============================================================================
# Target rules for targets named httpd

# Build rule for target.
httpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httpd
.PHONY : httpd

# fast build rule for target.
httpd/fast:
	$(MAKE) -f third_party/http/CMakeFiles/httpd.dir/build.make third_party/http/CMakeFiles/httpd.dir/build
.PHONY : httpd/fast

#=============================================================================
# Target rules for targets named lib/x86_64-linux-gnu/bee/lpeg

# Build rule for target.
lib/x86_64-linux-gnu/bee/lpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib/x86_64-linux-gnu/bee/lpeg
.PHONY : lib/x86_64-linux-gnu/bee/lpeg

# fast build rule for target.
lib/x86_64-linux-gnu/bee/lpeg/fast:
	$(MAKE) -f third_party/lpeg/CMakeFiles/lib/x86_64-linux-gnu/bee/lpeg.dir/build.make third_party/lpeg/CMakeFiles/lib/x86_64-linux-gnu/bee/lpeg.dir/build
.PHONY : lib/x86_64-linux-gnu/bee/lpeg/fast

#=============================================================================
# Target rules for targets named lanes

# Build rule for target.
lanes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lanes
.PHONY : lanes

# fast build rule for target.
lanes/fast:
	$(MAKE) -f third_party/lanes/CMakeFiles/lanes.dir/build.make third_party/lanes/CMakeFiles/lanes.dir/build
.PHONY : lanes/fast

third_party/PMurHash.o: third_party/PMurHash.c.o
.PHONY : third_party/PMurHash.o

# target to build an object file
third_party/PMurHash.c.o:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/PMurHash.c.o
.PHONY : third_party/PMurHash.c.o

third_party/PMurHash.i: third_party/PMurHash.c.i
.PHONY : third_party/PMurHash.i

# target to preprocess a source file
third_party/PMurHash.c.i:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/PMurHash.c.i
.PHONY : third_party/PMurHash.c.i

third_party/PMurHash.s: third_party/PMurHash.c.s
.PHONY : third_party/PMurHash.s

# target to generate assembly for a file
third_party/PMurHash.c.s:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/PMurHash.c.s
.PHONY : third_party/PMurHash.c.s

third_party/base64.o: third_party/base64.c.o
.PHONY : third_party/base64.o

# target to build an object file
third_party/base64.c.o:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/base64.c.o
.PHONY : third_party/base64.c.o

third_party/base64.i: third_party/base64.c.i
.PHONY : third_party/base64.i

# target to preprocess a source file
third_party/base64.c.i:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/base64.c.i
.PHONY : third_party/base64.c.i

third_party/base64.s: third_party/base64.c.s
.PHONY : third_party/base64.s

# target to generate assembly for a file
third_party/base64.c.s:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/base64.c.s
.PHONY : third_party/base64.c.s

third_party/bee_eio.o: third_party/bee_eio.c.o
.PHONY : third_party/bee_eio.o

# target to build an object file
third_party/bee_eio.c.o:
	$(MAKE) -f CMakeFiles/eio.dir/build.make CMakeFiles/eio.dir/third_party/bee_eio.c.o
.PHONY : third_party/bee_eio.c.o

third_party/bee_eio.i: third_party/bee_eio.c.i
.PHONY : third_party/bee_eio.i

# target to preprocess a source file
third_party/bee_eio.c.i:
	$(MAKE) -f CMakeFiles/eio.dir/build.make CMakeFiles/eio.dir/third_party/bee_eio.c.i
.PHONY : third_party/bee_eio.c.i

third_party/bee_eio.s: third_party/bee_eio.c.s
.PHONY : third_party/bee_eio.s

# target to generate assembly for a file
third_party/bee_eio.c.s:
	$(MAKE) -f CMakeFiles/eio.dir/build.make CMakeFiles/eio.dir/third_party/bee_eio.c.s
.PHONY : third_party/bee_eio.c.s

third_party/bee_ev.o: third_party/bee_ev.c.o
.PHONY : third_party/bee_ev.o

# target to build an object file
third_party/bee_ev.c.o:
	$(MAKE) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/third_party/bee_ev.c.o
.PHONY : third_party/bee_ev.c.o

third_party/bee_ev.i: third_party/bee_ev.c.i
.PHONY : third_party/bee_ev.i

# target to preprocess a source file
third_party/bee_ev.c.i:
	$(MAKE) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/third_party/bee_ev.c.i
.PHONY : third_party/bee_ev.c.i

third_party/bee_ev.s: third_party/bee_ev.c.s
.PHONY : third_party/bee_ev.s

# target to generate assembly for a file
third_party/bee_ev.c.s:
	$(MAKE) -f CMakeFiles/ev.dir/build.make CMakeFiles/ev.dir/third_party/bee_ev.c.s
.PHONY : third_party/bee_ev.c.s

third_party/coro/coro.o: third_party/coro/coro.c.o
.PHONY : third_party/coro/coro.o

# target to build an object file
third_party/coro/coro.c.o:
	$(MAKE) -f CMakeFiles/coro.dir/build.make CMakeFiles/coro.dir/third_party/coro/coro.c.o
.PHONY : third_party/coro/coro.c.o

third_party/coro/coro.i: third_party/coro/coro.c.i
.PHONY : third_party/coro/coro.i

# target to preprocess a source file
third_party/coro/coro.c.i:
	$(MAKE) -f CMakeFiles/coro.dir/build.make CMakeFiles/coro.dir/third_party/coro/coro.c.i
.PHONY : third_party/coro/coro.c.i

third_party/coro/coro.s: third_party/coro/coro.c.s
.PHONY : third_party/coro/coro.s

# target to generate assembly for a file
third_party/coro/coro.c.s:
	$(MAKE) -f CMakeFiles/coro.dir/build.make CMakeFiles/coro.dir/third_party/coro/coro.c.s
.PHONY : third_party/coro/coro.c.s

third_party/crc32.o: third_party/crc32.c.o
.PHONY : third_party/crc32.o

# target to build an object file
third_party/crc32.c.o:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/crc32.c.o
.PHONY : third_party/crc32.c.o

third_party/crc32.i: third_party/crc32.c.i
.PHONY : third_party/crc32.i

# target to preprocess a source file
third_party/crc32.c.i:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/crc32.c.i
.PHONY : third_party/crc32.c.i

third_party/crc32.s: third_party/crc32.c.s
.PHONY : third_party/crc32.s

# target to generate assembly for a file
third_party/crc32.c.s:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/crc32.c.s
.PHONY : third_party/crc32.c.s

third_party/gopt/gopt.o: third_party/gopt/gopt.c.o
.PHONY : third_party/gopt/gopt.o

# target to build an object file
third_party/gopt/gopt.c.o:
	$(MAKE) -f CMakeFiles/gopt.dir/build.make CMakeFiles/gopt.dir/third_party/gopt/gopt.c.o
.PHONY : third_party/gopt/gopt.c.o

third_party/gopt/gopt.i: third_party/gopt/gopt.c.i
.PHONY : third_party/gopt/gopt.i

# target to preprocess a source file
third_party/gopt/gopt.c.i:
	$(MAKE) -f CMakeFiles/gopt.dir/build.make CMakeFiles/gopt.dir/third_party/gopt/gopt.c.i
.PHONY : third_party/gopt/gopt.c.i

third_party/gopt/gopt.s: third_party/gopt/gopt.c.s
.PHONY : third_party/gopt/gopt.s

# target to generate assembly for a file
third_party/gopt/gopt.c.s:
	$(MAKE) -f CMakeFiles/gopt.dir/build.make CMakeFiles/gopt.dir/third_party/gopt/gopt.c.s
.PHONY : third_party/gopt/gopt.c.s

third_party/lua-cjson/lua_cjson.o: third_party/lua-cjson/lua_cjson.c.o
.PHONY : third_party/lua-cjson/lua_cjson.o

# target to build an object file
third_party/lua-cjson/lua_cjson.c.o:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/third_party/lua-cjson/lua_cjson.c.o
.PHONY : third_party/lua-cjson/lua_cjson.c.o

third_party/lua-cjson/lua_cjson.i: third_party/lua-cjson/lua_cjson.c.i
.PHONY : third_party/lua-cjson/lua_cjson.i

# target to preprocess a source file
third_party/lua-cjson/lua_cjson.c.i:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/third_party/lua-cjson/lua_cjson.c.i
.PHONY : third_party/lua-cjson/lua_cjson.c.i

third_party/lua-cjson/lua_cjson.s: third_party/lua-cjson/lua_cjson.c.s
.PHONY : third_party/lua-cjson/lua_cjson.s

# target to generate assembly for a file
third_party/lua-cjson/lua_cjson.c.s:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/third_party/lua-cjson/lua_cjson.c.s
.PHONY : third_party/lua-cjson/lua_cjson.c.s

third_party/lua-cjson/strbuf.o: third_party/lua-cjson/strbuf.c.o
.PHONY : third_party/lua-cjson/strbuf.o

# target to build an object file
third_party/lua-cjson/strbuf.c.o:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/third_party/lua-cjson/strbuf.c.o
.PHONY : third_party/lua-cjson/strbuf.c.o

third_party/lua-cjson/strbuf.i: third_party/lua-cjson/strbuf.c.i
.PHONY : third_party/lua-cjson/strbuf.i

# target to preprocess a source file
third_party/lua-cjson/strbuf.c.i:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/third_party/lua-cjson/strbuf.c.i
.PHONY : third_party/lua-cjson/strbuf.c.i

third_party/lua-cjson/strbuf.s: third_party/lua-cjson/strbuf.c.s
.PHONY : third_party/lua-cjson/strbuf.s

# target to generate assembly for a file
third_party/lua-cjson/strbuf.c.s:
	$(MAKE) -f CMakeFiles/cjson.dir/build.make CMakeFiles/cjson.dir/third_party/lua-cjson/strbuf.c.s
.PHONY : third_party/lua-cjson/strbuf.c.s

third_party/lua-yaml/api.o: third_party/lua-yaml/api.c.o
.PHONY : third_party/lua-yaml/api.o

# target to build an object file
third_party/lua-yaml/api.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/api.c.o
.PHONY : third_party/lua-yaml/api.c.o

third_party/lua-yaml/api.i: third_party/lua-yaml/api.c.i
.PHONY : third_party/lua-yaml/api.i

# target to preprocess a source file
third_party/lua-yaml/api.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/api.c.i
.PHONY : third_party/lua-yaml/api.c.i

third_party/lua-yaml/api.s: third_party/lua-yaml/api.c.s
.PHONY : third_party/lua-yaml/api.s

# target to generate assembly for a file
third_party/lua-yaml/api.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/api.c.s
.PHONY : third_party/lua-yaml/api.c.s

third_party/lua-yaml/b64.o: third_party/lua-yaml/b64.c.o
.PHONY : third_party/lua-yaml/b64.o

# target to build an object file
third_party/lua-yaml/b64.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/b64.c.o
.PHONY : third_party/lua-yaml/b64.c.o

third_party/lua-yaml/b64.i: third_party/lua-yaml/b64.c.i
.PHONY : third_party/lua-yaml/b64.i

# target to preprocess a source file
third_party/lua-yaml/b64.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/b64.c.i
.PHONY : third_party/lua-yaml/b64.c.i

third_party/lua-yaml/b64.s: third_party/lua-yaml/b64.c.s
.PHONY : third_party/lua-yaml/b64.s

# target to generate assembly for a file
third_party/lua-yaml/b64.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/b64.c.s
.PHONY : third_party/lua-yaml/b64.c.s

third_party/lua-yaml/dumper.o: third_party/lua-yaml/dumper.c.o
.PHONY : third_party/lua-yaml/dumper.o

# target to build an object file
third_party/lua-yaml/dumper.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/dumper.c.o
.PHONY : third_party/lua-yaml/dumper.c.o

third_party/lua-yaml/dumper.i: third_party/lua-yaml/dumper.c.i
.PHONY : third_party/lua-yaml/dumper.i

# target to preprocess a source file
third_party/lua-yaml/dumper.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/dumper.c.i
.PHONY : third_party/lua-yaml/dumper.c.i

third_party/lua-yaml/dumper.s: third_party/lua-yaml/dumper.c.s
.PHONY : third_party/lua-yaml/dumper.s

# target to generate assembly for a file
third_party/lua-yaml/dumper.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/dumper.c.s
.PHONY : third_party/lua-yaml/dumper.c.s

third_party/lua-yaml/emitter.o: third_party/lua-yaml/emitter.c.o
.PHONY : third_party/lua-yaml/emitter.o

# target to build an object file
third_party/lua-yaml/emitter.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/emitter.c.o
.PHONY : third_party/lua-yaml/emitter.c.o

third_party/lua-yaml/emitter.i: third_party/lua-yaml/emitter.c.i
.PHONY : third_party/lua-yaml/emitter.i

# target to preprocess a source file
third_party/lua-yaml/emitter.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/emitter.c.i
.PHONY : third_party/lua-yaml/emitter.c.i

third_party/lua-yaml/emitter.s: third_party/lua-yaml/emitter.c.s
.PHONY : third_party/lua-yaml/emitter.s

# target to generate assembly for a file
third_party/lua-yaml/emitter.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/emitter.c.s
.PHONY : third_party/lua-yaml/emitter.c.s

third_party/lua-yaml/loader.o: third_party/lua-yaml/loader.c.o
.PHONY : third_party/lua-yaml/loader.o

# target to build an object file
third_party/lua-yaml/loader.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/loader.c.o
.PHONY : third_party/lua-yaml/loader.c.o

third_party/lua-yaml/loader.i: third_party/lua-yaml/loader.c.i
.PHONY : third_party/lua-yaml/loader.i

# target to preprocess a source file
third_party/lua-yaml/loader.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/loader.c.i
.PHONY : third_party/lua-yaml/loader.c.i

third_party/lua-yaml/loader.s: third_party/lua-yaml/loader.c.s
.PHONY : third_party/lua-yaml/loader.s

# target to generate assembly for a file
third_party/lua-yaml/loader.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/loader.c.s
.PHONY : third_party/lua-yaml/loader.c.s

third_party/lua-yaml/lyaml.o: third_party/lua-yaml/lyaml.cc.o
.PHONY : third_party/lua-yaml/lyaml.o

# target to build an object file
third_party/lua-yaml/lyaml.cc.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/lyaml.cc.o
.PHONY : third_party/lua-yaml/lyaml.cc.o

third_party/lua-yaml/lyaml.i: third_party/lua-yaml/lyaml.cc.i
.PHONY : third_party/lua-yaml/lyaml.i

# target to preprocess a source file
third_party/lua-yaml/lyaml.cc.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/lyaml.cc.i
.PHONY : third_party/lua-yaml/lyaml.cc.i

third_party/lua-yaml/lyaml.s: third_party/lua-yaml/lyaml.cc.s
.PHONY : third_party/lua-yaml/lyaml.s

# target to generate assembly for a file
third_party/lua-yaml/lyaml.cc.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/lyaml.cc.s
.PHONY : third_party/lua-yaml/lyaml.cc.s

third_party/lua-yaml/parser.o: third_party/lua-yaml/parser.c.o
.PHONY : third_party/lua-yaml/parser.o

# target to build an object file
third_party/lua-yaml/parser.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/parser.c.o
.PHONY : third_party/lua-yaml/parser.c.o

third_party/lua-yaml/parser.i: third_party/lua-yaml/parser.c.i
.PHONY : third_party/lua-yaml/parser.i

# target to preprocess a source file
third_party/lua-yaml/parser.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/parser.c.i
.PHONY : third_party/lua-yaml/parser.c.i

third_party/lua-yaml/parser.s: third_party/lua-yaml/parser.c.s
.PHONY : third_party/lua-yaml/parser.s

# target to generate assembly for a file
third_party/lua-yaml/parser.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/parser.c.s
.PHONY : third_party/lua-yaml/parser.c.s

third_party/lua-yaml/reader.o: third_party/lua-yaml/reader.c.o
.PHONY : third_party/lua-yaml/reader.o

# target to build an object file
third_party/lua-yaml/reader.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/reader.c.o
.PHONY : third_party/lua-yaml/reader.c.o

third_party/lua-yaml/reader.i: third_party/lua-yaml/reader.c.i
.PHONY : third_party/lua-yaml/reader.i

# target to preprocess a source file
third_party/lua-yaml/reader.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/reader.c.i
.PHONY : third_party/lua-yaml/reader.c.i

third_party/lua-yaml/reader.s: third_party/lua-yaml/reader.c.s
.PHONY : third_party/lua-yaml/reader.s

# target to generate assembly for a file
third_party/lua-yaml/reader.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/reader.c.s
.PHONY : third_party/lua-yaml/reader.c.s

third_party/lua-yaml/scanner.o: third_party/lua-yaml/scanner.c.o
.PHONY : third_party/lua-yaml/scanner.o

# target to build an object file
third_party/lua-yaml/scanner.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/scanner.c.o
.PHONY : third_party/lua-yaml/scanner.c.o

third_party/lua-yaml/scanner.i: third_party/lua-yaml/scanner.c.i
.PHONY : third_party/lua-yaml/scanner.i

# target to preprocess a source file
third_party/lua-yaml/scanner.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/scanner.c.i
.PHONY : third_party/lua-yaml/scanner.c.i

third_party/lua-yaml/scanner.s: third_party/lua-yaml/scanner.c.s
.PHONY : third_party/lua-yaml/scanner.s

# target to generate assembly for a file
third_party/lua-yaml/scanner.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/scanner.c.s
.PHONY : third_party/lua-yaml/scanner.c.s

third_party/lua-yaml/writer.o: third_party/lua-yaml/writer.c.o
.PHONY : third_party/lua-yaml/writer.o

# target to build an object file
third_party/lua-yaml/writer.c.o:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/writer.c.o
.PHONY : third_party/lua-yaml/writer.c.o

third_party/lua-yaml/writer.i: third_party/lua-yaml/writer.c.i
.PHONY : third_party/lua-yaml/writer.i

# target to preprocess a source file
third_party/lua-yaml/writer.c.i:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/writer.c.i
.PHONY : third_party/lua-yaml/writer.c.i

third_party/lua-yaml/writer.s: third_party/lua-yaml/writer.c.s
.PHONY : third_party/lua-yaml/writer.s

# target to generate assembly for a file
third_party/lua-yaml/writer.c.s:
	$(MAKE) -f CMakeFiles/yaml.dir/build.make CMakeFiles/yaml.dir/third_party/lua-yaml/writer.c.s
.PHONY : third_party/lua-yaml/writer.c.s

third_party/proctitle.o: third_party/proctitle.c.o
.PHONY : third_party/proctitle.o

# target to build an object file
third_party/proctitle.c.o:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/proctitle.c.o
.PHONY : third_party/proctitle.c.o

third_party/proctitle.i: third_party/proctitle.c.i
.PHONY : third_party/proctitle.i

# target to preprocess a source file
third_party/proctitle.c.i:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/proctitle.c.i
.PHONY : third_party/proctitle.c.i

third_party/proctitle.s: third_party/proctitle.c.s
.PHONY : third_party/proctitle.s

# target to generate assembly for a file
third_party/proctitle.c.s:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/proctitle.c.s
.PHONY : third_party/proctitle.c.s

third_party/qsort_arg_mt.o: third_party/qsort_arg_mt.c.o
.PHONY : third_party/qsort_arg_mt.o

# target to build an object file
third_party/qsort_arg_mt.c.o:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/qsort_arg_mt.c.o
.PHONY : third_party/qsort_arg_mt.c.o

third_party/qsort_arg_mt.i: third_party/qsort_arg_mt.c.i
.PHONY : third_party/qsort_arg_mt.i

# target to preprocess a source file
third_party/qsort_arg_mt.c.i:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/qsort_arg_mt.c.i
.PHONY : third_party/qsort_arg_mt.c.i

third_party/qsort_arg_mt.s: third_party/qsort_arg_mt.c.s
.PHONY : third_party/qsort_arg_mt.s

# target to generate assembly for a file
third_party/qsort_arg_mt.c.s:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/qsort_arg_mt.c.s
.PHONY : third_party/qsort_arg_mt.c.s

third_party/sha1.o: third_party/sha1.c.o
.PHONY : third_party/sha1.o

# target to build an object file
third_party/sha1.c.o:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/sha1.c.o
.PHONY : third_party/sha1.c.o

third_party/sha1.i: third_party/sha1.c.i
.PHONY : third_party/sha1.i

# target to preprocess a source file
third_party/sha1.c.i:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/sha1.c.i
.PHONY : third_party/sha1.c.i

third_party/sha1.s: third_party/sha1.c.s
.PHONY : third_party/sha1.s

# target to generate assembly for a file
third_party/sha1.c.s:
	$(MAKE) -f CMakeFiles/misc.dir/build.make CMakeFiles/misc.dir/third_party/sha1.c.s
.PHONY : third_party/sha1.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... build_bundled_libs"
	@echo "... cjson"
	@echo "... coro"
	@echo "... edit_cache"
	@echo "... eio"
	@echo "... ev"
	@echo "... gopt"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... libluajit"
	@echo "... libsham"
	@echo "... list_install_components"
	@echo "... misc"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... tags"
	@echo "... yaml"
	@echo "... bee"
	@echo "... core"
	@echo "... generate_lua_sources"
	@echo "... ragel"
	@echo "... server"
	@echo "... generate_module_api"
	@echo "... msgpuck"
	@echo "... bit"
	@echo "... bitset"
	@echo "... small"
	@echo "... salad"
	@echo "... db"
	@echo "... db_generate_lua_sources"
	@echo "... bin2c"
	@echo "... txt2c"
	@echo "... man-beectl"
	@echo "... test"
	@echo "... test-force"
	@echo "... module_api"
	@echo "... arena_mt.test"
	@echo "... base64.test"
	@echo "... bit.test"
	@echo "... bitset_basic.test"
	@echo "... bitset_index.test"
	@echo "... bitset_iterator.test"
	@echo "... bps_tree.test"
	@echo "... bps_tree_itr.test"
	@echo "... coio.test"
	@echo "... fiber.test"
	@echo "... fiber_stress.test"
	@echo "... find_path.test"
	@echo "... fiob.test"
	@echo "... guava.test"
	@echo "... int96.test"
	@echo "... ipc.test"
	@echo "... lf_lifo.test"
	@echo "... light.test"
	@echo "... matras.test"
	@echo "... mempool.test"
	@echo "... mhash.test"
	@echo "... mhash_bytemap.test"
	@echo "... msgpack.test"
	@echo "... queue.test"
	@echo "... quota.test"
	@echo "... region.test"
	@echo "... rlist.test"
	@echo "... rope.test"
	@echo "... rope_avl.test"
	@echo "... rope_basic.test"
	@echo "... rope_stress.test"
	@echo "... rtree.test"
	@echo "... rtree_itr.test"
	@echo "... scramble.test"
	@echo "... slab_arena.test"
	@echo "... slab_cache.test"
	@echo "... small_alloc.test"
	@echo "... uri.test"
	@echo "... vclock.test"
	@echo "... man-bee"
	@echo "... httpd"
	@echo "... lib/x86_64-linux-gnu/bee/lpeg"
	@echo "... lanes"
	@echo "... third_party/PMurHash.o"
	@echo "... third_party/PMurHash.i"
	@echo "... third_party/PMurHash.s"
	@echo "... third_party/base64.o"
	@echo "... third_party/base64.i"
	@echo "... third_party/base64.s"
	@echo "... third_party/bee_eio.o"
	@echo "... third_party/bee_eio.i"
	@echo "... third_party/bee_eio.s"
	@echo "... third_party/bee_ev.o"
	@echo "... third_party/bee_ev.i"
	@echo "... third_party/bee_ev.s"
	@echo "... third_party/coro/coro.o"
	@echo "... third_party/coro/coro.i"
	@echo "... third_party/coro/coro.s"
	@echo "... third_party/crc32.o"
	@echo "... third_party/crc32.i"
	@echo "... third_party/crc32.s"
	@echo "... third_party/gopt/gopt.o"
	@echo "... third_party/gopt/gopt.i"
	@echo "... third_party/gopt/gopt.s"
	@echo "... third_party/lua-cjson/lua_cjson.o"
	@echo "... third_party/lua-cjson/lua_cjson.i"
	@echo "... third_party/lua-cjson/lua_cjson.s"
	@echo "... third_party/lua-cjson/strbuf.o"
	@echo "... third_party/lua-cjson/strbuf.i"
	@echo "... third_party/lua-cjson/strbuf.s"
	@echo "... third_party/lua-yaml/api.o"
	@echo "... third_party/lua-yaml/api.i"
	@echo "... third_party/lua-yaml/api.s"
	@echo "... third_party/lua-yaml/b64.o"
	@echo "... third_party/lua-yaml/b64.i"
	@echo "... third_party/lua-yaml/b64.s"
	@echo "... third_party/lua-yaml/dumper.o"
	@echo "... third_party/lua-yaml/dumper.i"
	@echo "... third_party/lua-yaml/dumper.s"
	@echo "... third_party/lua-yaml/emitter.o"
	@echo "... third_party/lua-yaml/emitter.i"
	@echo "... third_party/lua-yaml/emitter.s"
	@echo "... third_party/lua-yaml/loader.o"
	@echo "... third_party/lua-yaml/loader.i"
	@echo "... third_party/lua-yaml/loader.s"
	@echo "... third_party/lua-yaml/lyaml.o"
	@echo "... third_party/lua-yaml/lyaml.i"
	@echo "... third_party/lua-yaml/lyaml.s"
	@echo "... third_party/lua-yaml/parser.o"
	@echo "... third_party/lua-yaml/parser.i"
	@echo "... third_party/lua-yaml/parser.s"
	@echo "... third_party/lua-yaml/reader.o"
	@echo "... third_party/lua-yaml/reader.i"
	@echo "... third_party/lua-yaml/reader.s"
	@echo "... third_party/lua-yaml/scanner.o"
	@echo "... third_party/lua-yaml/scanner.i"
	@echo "... third_party/lua-yaml/scanner.s"
	@echo "... third_party/lua-yaml/writer.o"
	@echo "... third_party/lua-yaml/writer.i"
	@echo "... third_party/lua-yaml/writer.s"
	@echo "... third_party/proctitle.o"
	@echo "... third_party/proctitle.i"
	@echo "... third_party/proctitle.s"
	@echo "... third_party/qsort_arg_mt.o"
	@echo "... third_party/qsort_arg_mt.i"
	@echo "... third_party/qsort_arg_mt.s"
	@echo "... third_party/sha1.o"
	@echo "... third_party/sha1.i"
	@echo "... third_party/sha1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

