const char errno_lua[] =
"-- errno.lua (internal file)\n"
"\n"
"do\n"
"\n"
"local ffi = require 'ffi'\n"
"\n"
"ffi.cdef[[\n"
"    char *strerror(int errnum);\n"
"    int errno_get();\n"
"    int errno_set(int new_errno);\n"
"]]\n"
"\n"
"local exports = require('errno')\n"
"exports.strerror = function(errno)\n"
"    if errno == nil then\n"
"        errno = ffi.C.errno_get()\n"
"    end\n"
"    return ffi.string(ffi.C.strerror(tonumber(errno)))\n"
"end\n"
"\n"
"setmetatable(exports, {\n"
"    __newindex  = function() error(\"Can't create new errno constants\") end,\n"
"    __call = function(self, new_errno)\n"
"        local res\n"
"        if new_errno then\n"
"            return ffi.C.errno_set(new_errno)\n"
"        end\n"
"        return ffi.C.errno_get()\n"
"    end\n"
"})\n"
"\n"
"end\n"
""
;
