const char fiber_lua[] =
"-- fiber.lua (internal file)\n"
"\n"
"local fiber = require('fiber')\n"
"local ffi = require('ffi')\n"
"ffi.cdef[[\n"
"double\n"
"fiber_time(void);\n"
"uint64_t\n"
"fiber_time64(void);\n"
"]]\n"
"\n"
"local function fiber_time()\n"
"    return tonumber(ffi.C.fiber_time())\n"
"end\n"
"\n"
"local function fiber_time64()\n"
"    return ffi.C.fiber_time64()\n"
"end\n"
"\n"
"fiber.time = fiber_time\n"
"fiber.time64 = fiber_time64\n"
"return fiber\n"
""
;
