const char help_lua[] =
"local doc = require('help.en_US')\n"
"\n"
"help = {}\n"
"help[1] = {}\n"
"help[1][\"Help topics\"] = { \"Basics\", \"Administration\" }\n"
"help[2] = \"To get help on a topic, type help('topic') (with quotes)\"\n"
"help[3] = \"To get help on a function/object, type help(function) (without quotes)\"\n"
"help[4] = \"To start tutorial, type tutorial()\"\n"
"\n"
"tutorial = {}\n"
"tutorial[1] = help[4]\n"
"\n"
"local help_function_data = {};\n"
"help_function_data[\"Administration\"] = {}\n"
"help_function_data[\"Administration\"][\"Server administrative commands\"] =\n"
"{\t\t\"db.snapshot()\",\n"
"\t\t\"db.info()\",\n"
"\t\t\"db.stat()\",\n"
"\t\t\"db.slab.info()\",\n"
"\t\t\"db.slab.check()\",\n"
"\t\t\"db.fiber.info()\",\n"
"\t\t\"db.plugin.info()\",\n"
"\t\t\"db.cfg()\",\n"
"\t\t\"db.coredump()\"\n"
"}\n"
"help_function_data[\"Basics\"] = \"First thing to be done before any database object can be created, is calling db.cfg() to configure and bootstrap the database instance. Once this is done, define database objects using db.schema, for example type db.schema.space.create('test') to create space 'test'. To add an index on a space, type db.space.test:create_index(). With an index, the space can accept tuples. Insert a tuple with db.space.test:insert{1, 'First tuple'}\"\n"
"\n"
"local help_object_data = {}\n"
"\n"
"local function help_call(table, param)\n"
"    if type(param) == 'string' then\n"
"        if help_function_data[param] ~= nil then\n"
"            return help_function_data[param]\n"
"        end\n"
"    end\n"
"    if type(param) == 'table' then\n"
"        if help_object_data[param] ~= nil then\n"
"            return help_object_data[param]\n"
"        end\n"
"    end\n"
"    if param ~= nil then\n"
"        return \"Help object not found\"\n"
"    end\n"
"    return table\n"
"end\n"
"\n"
"setmetatable(help, { __call = help_call })\n"
"\n"
"local screen_id = 1;\n"
"\n"
"local function tutorial_call(table, action)\n"
"    if action == 'start' then\n"
"        screen_id = 1;\n"
"    elseif action == 'next' or action == 'more' then\n"
"        screen_id = screen_id + 1\n"
"    elseif action == 'prev' then\n"
"        screen_id = screen_id - 1\n"
"    elseif type(action) == 'number' and action % 1 == 0 then\n"
"        screen_id = tonumber(action)\n"
"    elseif action ~= nil then\n"
"        error('Usage: tutorial(\"start\" | \"next\" | \"prev\" | 1 .. '..\n"
"            #doc.tutorial..')')\n"
"    end\n"
"    if screen_id < 1 then\n"
"        screen_id = 1\n"
"    elseif screen_id > #doc.tutorial then\n"
"        screen_id = #doc.tutorial\n"
"    end\n"
"    return doc.tutorial[screen_id]\n"
"end\n"
"\n"
"setmetatable(tutorial, { __call = tutorial_call })\n"
"\n"
"return {\n"
"    help = help;\n"
"    tutorial= tutorial;\n"
"}\n"
""
;
