#ifndef BEE_CONFIG_H_INCLUDED
#define BEE_CONFIG_H_INCLUDED
/*
 * This file is generated by CMake. The original file is called
 * config.h.cmake. Please do not modify.
 */
/** \cond public */
/*
 * A string with major-minor-patch-commit-id identifier of the
 * release.
 */
#define PACKAGE_VERSION "1.6.5-150-gdc14e23"
#define PACKAGE_VERSION_MAJOR 1
#define PACKAGE_VERSION_MINOR 6
#define PACKAGE_VERSION_PATCH 5

/** \endcond public */

#define PACKAGE "Bee"
/*  Defined if building for Linux */
#define TARGET_OS_LINUX 1
/*  Defined if building for FreeBSD */
/* #undef TARGET_OS_FREEBSD */
/*  Defined if building for Darwin */
/* #undef TARGET_OS_DARWIN */
/*
 * Defined if gcov instrumentation should be enabled.
 */
/* #undef ENABLE_GCOV */
/*
 * Defined if configured with ENABLE_TRACE (debug trace into
 * a file specified by BEE_TRACE environment variable.
 */
#define ENABLE_TRACE 1
/*
 * Defined if configured with ENABLE_BACKTRACE ('show fiber'
 * showing fiber call stack.
 */
#define ENABLE_BACKTRACE 1
/*
 * Set if the system has bfd.h header and GNU bfd library.
 */
/* #undef HAVE_BFD */
#define HAVE_MAP_ANON 1
#define HAVE_MAP_ANONYMOUS 1
#if !defined(HAVE_MAP_ANONYMOUS) && defined(HAVE_MAP_ANON)
/*
 * MAP_ANON is deprecated, MAP_ANONYMOUS should be used instead.
 * Unfortunately, it's not universally present (e.g. not present
 * on FreeBSD.
 */
#define MAP_ANONYMOUS MAP_ANON
#endif
/*
 * Defined if O_DSYNC mode exists for open(2).
 */
#define HAVE_O_DSYNC 1
#if defined(HAVE_O_DSYNC)
    #define WAL_SYNC_FLAG O_DSYNC
#else
    #define WAL_SYNC_FLAG O_SYNC
#endif
/*
 * Defined if fdatasync(2) call is present.
 */
#define HAVE_FDATASYNC 1

#ifndef HAVE_FDATASYNC
	#define fdatasync fsync
#endif

/*
 * Defined if this platform has BSD specific funopen()
 */
/* #undef HAVE_FUNOPEN */

/*
 * Defined if this platform has GNU specific fopencookie()
 */
#define HAVE_FOPENCOOKIE 1

/*
 * Defined if this platform has GNU specific memmem().
 */
#define HAVE_MEMMEM 1
/*
 * Defined if this platform has GNU specific memrchr().
 */
#define HAVE_MEMRCHR 1
/*
 * Defined if this platform has sendfile(..).
 */
#define HAVE_SENDFILE 1
/*
 * Defined if this platform has Linux specific sendfile(..).
 */
#define HAVE_SENDFILE_LINUX 1
/*
 * Defined if this platform has BSD specific sendfile(..).
 */
/* #undef HAVE_SENDFILE_BSD */
/*
 * Set if this is a GNU system and libc has __libc_stack_end.
 */
#define HAVE_LIBC_STACK_END 1
/*
 * Defined if this is a big-endian system.
 */
/* #undef HAVE_BYTE_ORDER_BIG_ENDIAN */
/*
 * Defined if this platform supports openmp and it is enabled
 */
#define HAVE_OPENMP 1
/*
*  Defined if compatible with GNU readline installed.
*/
#define HAVE_GNU_READLINE 1

/*
 * Defined if `st_mtim' is a member of `struct stat'.
 */
#define HAVE_STRUCT_STAT_ST_MTIM 1

/*
 * Defined if `st_mtimensec' is a member of `struct stat'.
 */
/* #undef HAVE_STRUCT_STAT_ST_MTIMENSEC */

/*
 * Set if compiler has __builtin_XXX methods.
 */
#define HAVE_BUILTIN_CTZ 1
#define HAVE_BUILTIN_CTZLL 1
#define HAVE_BUILTIN_CLZ 1
#define HAVE_BUILTIN_CLZLL 1
#define HAVE_BUILTIN_POPCOUNT 1
#define HAVE_BUILTIN_POPCOUNTLL 1
#define HAVE_BUILTIN_BSWAP32 1
#define HAVE_BUILTIN_BSWAP64 1
/* #undef HAVE_FFSL */
/* #undef HAVE_FFSLL */

/*
 * pthread have problems with -std=c99
 */
/* #undef HAVE_NON_C99_PTHREAD_H */

#define ENABLE_BUNDLED_LIBEV 1
#define ENABLE_BUNDLED_LIBEIO 1
#define ENABLE_BUNDLED_LIBCORO 1

/* #undef HAVE_PTHREAD_YIELD */
#define HAVE_SCHED_YIELD 1

#define HAVE_PRCTL_H 1

#define HAVE_OPEN_MEMSTREAM 1
#define HAVE_FMEMOPEN 1

/* #undef HAVE_UUIDGEN */

/** \cond public */

/*
 * predefined /etc directory prefix.
 */
#define SYSCONF_DIR "etc"
#define INSTALL_PREFIX "/usr/local"
#define BUILD_TYPE "Debug"
#define BUILD_INFO "Linux-x86_64-Debug"
#define BUILD_OPTIONS "cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_TRACE=ON -DENABLE_BACKTRACE=ON"
#define COMPILER_INFO "/usr/bin/cc /usr/bin/c++"
#define BEE_C_FLAGS " -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -fno-gnu89-inline -Werror"
#define BEE_CXX_FLAGS " -fno-omit-frame-pointer -fno-stack-protector -fexceptions -funwind-tables -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-sign-compare -Wno-strict-aliasing -Wno-invalid-offsetof -Werror"

/*
 * Modules
 */
#define MODULE_LIBDIR "/usr/local/lib/x86_64-linux-gnu/bee"
#define MODULE_LUADIR "/usr/local/share/bee"
#define MODULE_INCLUDEDIR "/usr/local/include/bee"
#define MODULE_LUAPATH "/usr/local/share/bee/?.lua;/usr/local/share/bee/?/init.lua"
#define MODULE_LIBPATH "/usr/local/lib/x86_64-linux-gnu/bee/?.so"

/** \endcond public */

#define DEFAULT_CFG_FILENAME "bee.cfg"
#define DEFAULT_CFG SYSCONF_DIR "/" DEFAULT_CFG_FILENAME

/*
 * vim: syntax=c
 */
#endif /* BEE_CONFIG_H_INCLUDED */
